service: aws-rest-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: hello.greet
    description: Hello World!

  createCandidate:
    handler: api/candidate.create
    memorySize: 128
    description: Create a candidate
    events:
      - http:
          path: candidates
          method: post
